name: code_generator
description: A code generator demo.
version: 1.0.0
homepage: https://github.com/rhymelph
author: rhymelph <rhymelph@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
