name: code_generator_gen
description: A code generator build demo
version: 1.0.0
homepage: https://github.com/rhymelph
author: rhymelph <rhymelph@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  code_generator:
    path: ../code_generator/ #code_generator包位于该包的同级目录下

dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
