name: code_generator_example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: rhyme <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  code_generator:
    path: ../code_generator/

dev_dependencies:
  test: ^1.0.0
  build_runner: 1.0.0
  code_generator_gen:
      path: ../code_generator_gen/
